global using diabloblazor;
global using diabloblazor.Enums;
global using diabloblazor.Extensions;
global using diabloblazor.Imports;
global using diabloblazor.JsonConverters;
global using diabloblazor.Models;
global using diabloblazor.Pages;
global using diabloblazor.Services;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Forms;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using Microsoft.AspNetCore.Components.WebAssembly.Http;
global using Microsoft.JSInterop;
global using System.Collections.ObjectModel;
global using System.Runtime.InteropServices;
global using System.Runtime.InteropServices.JavaScript;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using static diabloblazor.Shared.Utils;
global using static System.Math;
